docs/installation.md
=> fix installation.md bug

docs/Concepts/application.md, docs/Concepts/cluster.md, docs/Concepts/devspace.md, docs/Concepts/service.md, docs/Concepts/user.md, docs/Deployment/deployment-tke.md, docs/References/architecture.md, docs/References/port-forward.md, docs/Tutorials/nocalhost-with-minikube.md, docs/Tutorials/nocalhost-without-ide-plugin.md, docs/Tutorials/plugin-best-practices.md, docs/Tutorials/vscode-plugin.md, docs/deployment.md, docs/getting-started.md, docs/installation.md, docs/zh/Concepts/application.md, docs/zh/Concepts/cluster.md, docs/zh/Concepts/devcontainer.md, docs/zh/Concepts/devmode.md, docs/zh/Concepts/devspace.md, docs/zh/Concepts/service.md, docs/zh/Concepts/user.md, docs/zh/References/architecture.md, docs/zh/Tutorials/nocalhost-with-helm.md, docs/zh/Tutorials/nocalhost-with-k8s-manifests.md, docs/zh/deployment.md, docs/zh/getting-started.md, docs/zh/installation.md
=> click image can open new tab

docs/stylesheets/extra.css
=> Fixed the nav style error in the doc site

docs/zh/Blog/mdhow-to-debug-microservices-in-kubernetes-with-proxy-sidecar-or-service-mesh.md
如何调试 Kubernetes 中的微服务 ——proxy、sidecar 还是 service mesh？
=> Add a new blog

docs/guides/debug/remote-debug.md
Update the debug command of mvn under different jdk and spring boot versions
=> Update the debug command of mvn

i18n/en/code.json, i18n/zh-CN/code.json, src/pages/tools/index.module.scss
=> Feature/add tool page (#101)

docs/config/config-enhance.md, docs/config/config-overview.md, docs/config/config-spec.md, docs/config/config.md, i18n/en/code.json, src/pages/index.module.css, src/pages/tools/components/Card.tsx, src/pages/tools/components/RunAndDebug.tsx, src/pages/tools/components/Volume.tsx, src/pages/tools/index.module.scss, src/pages/tools/index.tsx, src/types/index.ts
style: fix tooltip && switch color
=> Feature/add tool page (#103)

src/pages/index.module.css
Fix the problem that the homepage width is too wide
=> fix: Fix the homepage width

i18n/en/code.json, i18n/zh-CN/code.json, src/constants/index.ts, src/pages/tools/components/FileSync.tsx, src/pages/tools/index.tsx, src/types/index.ts
=> feat: file sync add delete protection

src/pages/index.js, src/pages/tools/index.module.scss
=> fix: change style

src/pages/tools/index.tsx, src/util/index.ts
=> fix: validte err

babel.config.js, package.json, src/pages/tools/index.module.scss, src/pages/tools/index.tsx, yarn.lock
=> fix: antd style reqiure inneed and fix dark mode style

src/pages/index.module.css
=> fix: homepage style

src/components/VideoModal.js, src/pages/index.js, src/pages/index.module.scss
=> fix: dark mode style

src/pages/index.module.scss
=> feat: change font color

docs/guides/debug/remote-debug.md
https://nocalhost.coding.net/p/nocalhost/assignments/issues/949/detail
=> - fix: PHP remote debug port

docs/guides/debug/remote-debug.md, docs/guides/remote-run.md
https://nocalhost.coding.net/p/nocalhost/bug-tracking/issues/950/detail
=> - fix: Node.js run/debug

docs/guides/debug/vscode-debug.mdx
Signed-off-by: zhangjian <zhangjian@coding.net>
=> Update vscode debug

docs/guides/develop-service-crd.md, sidebars.js
Signed-off-by: vgjm <vgjm456@qq.com>
=> feat: translate guides/develop-service-crd into English

docs/guides/debug/vscode-debug.mdx
Signed-off-by: zhangjian <zhangjian@coding.net>
=> feat: Add vscode FAQ

src/constants/index.ts, src/pages/tools/components/FileSync.tsx, src/pages/tools/components/RunAndDebug.tsx, src/pages/tools/index.tsx, src/types/index.ts
=> style: fix select not expand when hover on icon

src/pages/tools/index.tsx
Signed-off-by: yuanganping <562720180@qq.com>
=> fix: set language

docs/guides/manage-cluster.md
=> fix: spell error

docs/quick-start.md
=> fix: quick start command spell error

docs/server/manage-app.md, docs/server/manage-cluster.md, docs/server/manage-devspace-iso.md, docs/server/manage-user.md, docs/server/nh-dep.md
change manage cluster, manage user, manage application and isolated cluster
Signed-off-by: vgjm <vgjm456@qq.com>
=> feat: complete nocalhost server section

docs/config/config-dev-container-en.md
feat：add imagePullPolicy 
Signed-off-by: 58GANJI-CORP\taoxin <taoxin@58.com>
=> add imagePullPolicy 

src/pages/tools/index.tsx
=> fix: env var init

src/components/VideoModal.js, src/pages/index.js
=> fix: video play url

package.json, yarn.lock
Signed-off-by: zhangjian <zhangjian@coding.net>
=> chore: update "plugin-image-zoom" version

.github/workflows/document.yml
Signed-off-by: zhangjian <zhangjian@coding.net>
=> chore: update checks job

.github/workflows/document.yml
Signed-off-by: Yicai Yu <yuyicai@hotmail.com>
=> ci: add pull_request_target event

blog/rainbond-debug.md
Signed-off-by: Qi Zhang <smallqi1@163.com>
=> docs: add a new blog

src/pages/index.js, src/pages/index.module.scss, static/img/home/header-bg-blue-after.svg
There were a lot of style bugs when the home page was rewritten last time, this branch fixes some of the them, the main layout is fine now.
=> fix: style bugs of the home page since last rewrite
